### ISSUE TITLE
Feature Request: include/exclude based on annotations

### ISSUE THREAD

**Issue by samcday** [jeluard/semantic-versioning#56]
My company have a set of annotations we use on classes to express compatibility guarantees.

We have `@PublicSpi`, which means that we consider the "shape" (both public and protected fields / methods) of types annotated with it to be considered API. Thus, we support others to subclass / implement those types.

`@PublicApi`, on the other hand, guarantees only compatibility from callers (not implementors).

The analogy here is we'd expect `BACKWARD_COMPATIBLE_IMPLEMENTER` for types annotated with `@PublicSpi` and `BACKWARD_COMPATIBLE_USER` for types annotated with `@PublicApi`.

The current filtering mechanism doesn't provide fine-grained enough control for us to make the distinction on compatibility level requirements. Ideally, we'd be able to filter by a class-level annotation. Is this something you'd consider supporting, if we raised a PR to add this behaviour?

**Comment by jeluard** [comment]
Definitively open to a PR.

Do you have something specific in mind? Maybe some way to provide your own implementation of a `Filter` interface. The regexp could then be the default implementation.

**Comment by samcday** [comment]
Hadn't thought about specifics yet. I'm not quite sure how one would provide an implementation of something to a Maven plugin, since it's not actually in the projects classpath. As a first pass I was just thinking of adding `<includeAnnotations>` / `<excludeAnnotations>` config options, with fully qualified classnames of annotations to include / exclude. If we find there's more complex filtering mechanisms that people want we can refactor it later (perhaps using something like scannotation / [fast-classpath-scanner](https://github.com/lukehutch/fast-classpath-scanner) as the backend?)

**Comment by jeluard** [comment]
> I'm not quite sure how one would provide an implementation of something to a Maven plugin

I didn't try but it might be as easy as defining an extra `dependency` definition at the same level `enforcer-rule` is defined. `semantic-versioning` `enforcer-rule` already is a plugin of `maven-enforcer-plugin`.

I'd rather explore this before considering introducing `includeAnnotations`. Let me know if that make sense!

**Comment by mschonaker** [comment]
In my case, it would be nice to have a sort of @Experimental annotation, which would exclude methods and/or classes and/or fields from the compatibility comparison.

The canonical name of this annotation should be optionally parameterized, in order to avoid having to include a dependency in the code only having one annotation.

Also, it would be nice to optionally parameterize the rule, so it complains if any remainder annotation is present during a major and minor releases (not patches).

**Comment by jeluard** [comment]
@mschonaker I would encourage you to consider [japicmd](https://github.com/siom79/japicmp), I don't plan to add new features to this library. Sorry!

**Comment by mschonaker** [comment]
Okay. Thank you for the reference.
